import { images } from '../../constants';

const worksData = [
  {
    id: 1,
    title: 'Modern UI/UX Website',
    description: 'This is modern websites demonstrating the design and layout of modern website and is built using CSS3 and react.',
    projectLink: 'https://modern-website-cyan.vercel.app/',
    codeLink: 'codeLink',
    imgUrl: images.dev,
    tags: 'Web App',
    tag: 'website tag',
  },
  {
    id: 2,
    title: 'React Youtube Clone',
    description: 'React youtube clone that demonstrates all the youtube functionalities',
    projectLink: 'https://youtube-clone-five-liart.vercel.app/',
    codeLink: 'code link',
    imgUrl: images.bankWebsite,
    tags: 'React JS',
    tag: 'Website tag',
  },
  {
    id: 3,
    title: 'React Fitness Application',
    description: 'This is a reactjs fitness application that is designed using react,material-ui,react-router-dom,and integrated rapidapi exerciseDB. It demonstrating multiple exercising for the user.',
    projectLink: 'https://fitness-application-ecru.vercel.app/',
    codeLink: 'Code Link',
    imgUrl: images.fitness,
    tags: 'React JS',
    tag: 'Application tag',
  },
  {
    id: 4,
    title: 'React Dashboard Application',
    description: 'This is a reactjs dashboard application with theming,tables,charts,calendar,kanban and more that is designed using react, syncfusion,react-icons,react-router-dom, and tailwind-css.',
    projectLink: 'https://react-dashboard-app-mu.vercel.app/',
    codeLink: 'code link',
    imgUrl: images.dashboard,
    tags: 'React JS',
    tag: 'Application tag',
  },
  {
    id: 5,
    title: 'Modern React Real Estate Application',
    description: 'This a nextjs real estate application that demonstrates different real states from the UAE in South African currency.Designed using the css framework using chakra-ui and it also integrates an api from rapidapi.The Application is still under construction',
    projectLink: 'https://youtube-clone-five-liart.vercel.app/',
    codeLink: 'Code Link',
    imgUrl: images.realEstate,
    tags: 'Next JS',
    tag: 'Application tag',
  },
  {
    id: 6,
    title: 'Modern Crypto and Smart Contracts Application',
    description: 'This is a cryptocurrency application that demonstrates the UniSwap platform functionality.The Application is still under construction',
    projectLink: 'https://youtube-clone-five-liart.vercel.app/',
    codeLink: 'Code Link',
    imgUrl: images.realEstate,
    tags: 'Next JS',
    tag: 'Application tag',
  },
];
export default worksData;
