import { images } from '../../constants';

const worksData = [
  {
    id: 1,
    title: 'Modern UI/UX Website',
    description: 'This is modern websites demonstrating the design and layout of modern website and is built using CSS3 and react.',
    projectLink: 'https://modern-website-cyan.vercel.app/',
    codeLink: 'https://github.com/Bongumenzi2724',
    imgUrl: images.dev,
    tags: 'Web App',
    tag: 'website tag',
  },
  {
    id: 2,
    title: 'React Youtube Clone',
    description: 'React youtube clone that demonstrates all the youtube functionalities',
    projectLink: 'https://youtube-clone-five-liart.vercel.app/',
    codeLink: 'https://github.com/Bongumenzi2724',
    imgUrl: images.bankWebsite,
    tags: 'React JS',
    tag: 'Website tag',
  },
  {
    id: 3,
    title: 'React Fitness Application',
    description: 'This is a reactjs fitness application that is designed using react,material-ui,react-router-dom,and integrated rapidapi exerciseDB. It demonstrating multiple exercising for the user.',
    projectLink: 'https://fitness-application-ecru.vercel.app/',
    codeLink: 'https://github.com/Bongumenzi2724',
    imgUrl: images.fitness,
    tags: 'React JS',
    tag: 'Application tag',
  },
  {
    id: 4,
    title: 'React Dashboard Application',
    description: 'This is a reactjs dashboard application with theming,tables,charts,calendar,kanban and more that is designed using react, syncfusion,react-icons,react-router-dom, and tailwind-css.',
    projectLink: 'https://react-dashboard-app-mu.vercel.app/',
    codeLink: 'https://github.com/Bongumenzi2724',
    imgUrl: images.dashboard,
    tags: 'React JS',
    tag: 'Application tag',
  },
  {
    id: 5,
    title: 'Modern React Real Estate Application(Under Construction)',
    description: 'This a nextjs real estate application that demonstrates different real states from the UAE in South African currency.Designed using the css framework using chakra-ui and it also integrates an api from rapidapi.The Application is still under construction',
    projectLink: 'https://personal-portfolio-lovat-alpha.vercel.app/',
    codeLink: 'https://github.com/Bongumenzi2724',
    imgUrl: images.realEstate,
    tags: 'Next JS',
    tag: 'Application tag',
  },
  {
    id: 6,
    title: 'Modern Crypto and Smart Contracts Application(Under Construction)',
    description: 'This is a cryptocurrency application that demonstrates the UniSwap platform functionality.The Application is still under construction',
    projectLink: 'https://personal-portfolio-lovat-alpha.vercel.app/',
    codeLink: 'https://github.com/Bongumenzi2724',
    imgUrl: images.blockchain,
    tags: 'Web App',
    tag: 'Application tag',
  },
  {
    id: 7,
    title: 'Modern Music Streaming Application(Not Functional,API Update)',
    description: 'This is modern music streaming application that is similar to Spotify. It is created using ReactJS, material-ui, and RapidAPI API that provides data to the application. This application can be upgraded by using a paid api for a much more comprehensive music experience',
    projectLink: 'https://music-application-qn57.vercel.app/',
    codeLink: 'https://github.com/Bongumenzi2724',
    imgUrl: images.musicApp,
    tags: 'React JS',
    tag: 'Application tag',
  },
  {
    id: 8,
    title: 'Modern Metaverse website',
    description: 'This is a simple metaverse that display brief information about the metaverse. It has added animation that is implemented using a css-framework called framer-motion and ReactJS',
    projectLink: 'https://web3-metaverse-website.vercel.app/',
    codeLink: 'https://github.com/Bongumenzi2724',
    imgUrl: images.metaverse,
    tags: 'Next JS',
    tag: 'Application tag',
  },
  {
    id: 9,
    title: 'Blockchain Crowd funding Application',
    description: 'This is an exciting blockchain application built using ReactJS and use all advanced practices such as React Router,custom hooks, contextAPI and many more. Metamask cryptocurrency wallet is used to allow user to send ethereum crypto tokens to a specific campaign created to raised funds. All the web dev best practices are followed in the development of this application.',
    projectLink: 'https://web3-crowdfunding-project-three.vercel.app/',
    codeLink: 'https://github.com/Bongumenzi2724',
    imgUrl: images.MetaMask_Fox,
    tags: 'React JS',
    tag: 'Application tag',
  },
];
export default worksData;
